# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [1]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [2]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [4]:
# Checking the dimensions of the array
arr_3.ndim

2

In [5]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [7]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1, 11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [9]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5, 4)

# Checking the rows and columns in the created array
arr_6.shape

(5, 4)

In [15]:
# Stacking arr_5 and arr_6
np.hstack((arr_5, arr_6))

array([[ 1,  2, 20, 21, 22, 23],
       [ 3,  4, 24, 25, 26, 27],
       [ 5,  6, 28, 29, 30, 31],
       [ 7,  8, 32, 33, 34, 35],
       [ 9, 10, 36, 37, 38, 39]])

In [16]:
# Check the structure of arr_6
arr_6 = arr_6.reshape(10, 2)

In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [17]:
# Stacking arr_5 and arr_6
np.vstack((arr_5, arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [27]:
g = np.reshape(arr_5, (1,-1))

In [29]:
g.ndim

2

In [30]:
g

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [24]:
x =np.full((4,4),7)

In [35]:
np.reshape(x, (8,-2))

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])