# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
# importing the NumPy library

import numpy as np

In [5]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1,5)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [6]:
# checking the created array: np_1
print(np_1)

[1 2 3 4]


In [7]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [8]:
# data type of np_2
np_2.dtype

dtype('float64')

In [10]:
# specifying the data type of the array in the provided attribute
np_2 = np.zeros(5,'int')
np_2

array([0, 0, 0, 0, 0])

In [11]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [12]:
# check the dimension of the arrays
# array np_1
np_1.size

4

In [13]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [14]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5)

# checking the created array:np_3
print(np_3)

[1. 1. 1. 1. 1.]


In [15]:
# check the dimension of the arrays
# array np_2
np_2.ndim

1

In [16]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


In [20]:
# creating an array of fixed length
np_4 = np.linspace(1,10,5)

# checking the created array:np_4
print(np_4)

[ 1.    3.25  5.5   7.75 10.  ]


In [21]:
# checking the created array:np_1
np_1

array([1, 2, 3, 4])

In [22]:
# squaring the terms of np_1
np.power(np_1,2)

array([ 1,  4,  9, 16], dtype=int32)

In [23]:
# getting the absolute value of the elements
np.absolute(np.array([1,2,-1,-2]))

array([1, 2, 1, 2])

In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [26]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.empty(5)

# filling the empty array
np.multiply(x,4,out=y)

array([ 4.,  8., 12., 16., 20.])

In [27]:
# printing the output obtained above
y

array([ 4.,  8., 12., 16., 20.])

### Aggregation of array elements

In [28]:
# Reducing the elements to a single value based on addition
np.add.reduce(x)

15

In [32]:
# Cummulative addition of elements at each element
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [ ]:
np.linalg

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [33]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [34]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [35]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [36]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.93253066, 0.38497224, 0.35988138, 0.30913735],
       [0.75926761, 0.89939535, 0.94814086, 0.92767939],
       [0.98281821, 0.12356146, 0.64613527, 0.72833998]])

In [38]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[4, 8, 5, 4],
       [3, 9, 4, 5],
       [6, 3, 7, 8],
       [6, 5, 8, 0]])

In [58]:
ar = ([0, 1])
rar= [1, 0]

In [41]:
type(ar)

list

In [59]:
x = np.tile(ar,(4,2))
rev = np.tile(rar,2)

In [60]:
x[1::2]=rev

In [61]:
x

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])